# This is called on a succesful build

name: Build Image

on:
  pull_request:
    types:
      - closed
     
jobs:
  build-image:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Run test of App 
        run: echo "I built it!"
