# This is called on a succesful build

name: Build Image

on:
  pull_request:
    types:
      - closed
     
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Run test of App 
        run: echo "I built it!"
