name: Function App Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'App Tag to deploy'
        required: true
        default: 'v1.0.0'
      workspace:
        description: 'Environment to deploy to'
        required: true
        default: 'Dev'
        type: choice
        options:
          - Dev
          - Test
          - Pre-Prod
          - Prod
          - Load-Test

          
jobs:
  build:
    name: 'Function App Deploy'
    runs-on: ubuntu-latest
    environment: ${{ inputs.workspace }}
    steps:
      - name: Fetch release
        run:  wget ${{ github.event.repository.name }}/archive/refs/tags/${{ inputs.tag }}.zip
        
      - name: Deploy Function App
        run:  az functionapp deployment source config-zip --name ${{ vars.FAD_FUNCTION_APP_NAME }} --resource-group ${{ vars.FAD_RESOURCE_GROUP }} ${{ inputs.tag }}.zip
