name: oracle-reboot

on: 
  workflow_dispatch:
  schedule:
    - cron: '10 4 1 * *'

jobs:
  oracle-reboot:
    runs-on: ubuntu-latest
    name: Restart Instances
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
    steps:
      - name: Restart Instance 1
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: 'compute instance action --instance-id ocid1.instance.oc1.uk-london-1.anwgiljten2l5ticwgl5x3av6po2o34cl5agazijbcwiqcg53hjwgtpv2cja --action SOFTRESET'
          silent: 'False'
    
      - name: Restart Instance 2
        uses: oracle-actions/run-oci-cli-command@v1.1.1
        with:
          command: 'compute instance action --instance-id ocid1.instance.oc1.uk-london-1.anwgiljten2l5ticgnis2m3mtat6h5svwpt7hentzocxyznmtfa5wepezeaq --action SOFTRESET'
          silent: 'False'
