# This is called on a succesful build
name: Pass Between Steps

on:
  workflow_dispatch:

jobs:
  go-lint:
    name: Pass
    runs-on: ubuntu-22.04
    steps:
      - name: Create two lines in the output
        id: my-link
        run: |
          echo "Hello One"
          echo "Hello Two"

      - name: Output from my-link
        run: |
          echo "${{ steps.my-link.outputs.stdout }}"
