name: Show IP

on: [workflow_dispatch]

jobs:
  
  Show-IP:
    runs-on: ubuntu-latest
    steps:
      - name: Get the IP
        run: echo "theIP=$(curl https://ifconfig.co/)" >> $GITHUB_ENV
      - name: Echo the IP
        run: echo "Hello the IP is ${{ env.theIP }}"
