# Echo this task always runs - whatever the commit

name: Test App

on: 
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  test-app:
    runs-on: ubuntu-latest

    steps:
      - name: Run test of App 
        run: if [ $RANDOM -gt 20000 ]; then echo "I failed"; exit 1; else echo "I passed"; exit 0; fi
      
